version: '3.3'
services:
  db:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  timer_web:
    build:
      context: ../timer_ws
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
      - ../data:/code/data/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../frontend/build:/usr/share/nginx/html/
#      - ../docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - timer_web

volumes:
  postgres_data:
  static_value:
  media_value:
